### ISSUE TITLE
我想知道gitbook怎么加头像

### ISSUE THREAD

**Issue by WHYBBE** [wansho/wansho-gitbook#1]
#### 所以想问一下你能不能和我说一下具体是怎么配置的，谢谢！

**Comment by wansho** [comment]
@WHYBBE 
谢谢，我的 GitBook 不是自己架设的服务器，是直接将内容托管到的 [GitBook](https://www.gitbook.com/) 网站上。
具体你可以看一下我写的这篇教程：https://gitbook.wansho.cn/other-knowledge-notebook/tools/gitbook
